name: craft
description: Ceramic Sherd Classifier.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_ui_auth: ^1.13.0
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  google_maps_flutter: ^2.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^8.0.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - images/
  uses-material-design: true
  fonts: 
    - family: Uber
      fonts:
        - asset: fonts/UberMoveBold.otf
          weight: 700
        - asset: fonts/UberMoveMedium.otf
          weight: 500