name: craft
description: Ceramic Sherd Classifier.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  google_maps_flutter: ^2.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^8.0.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  image: ^3.3.0
  tflite_flutter_plus: ^0.0.1
  tflite_flutter_helper_plus: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - images/
    - images/Kanaa/
    - images/Black_Mesa/
    - images/Sosi/
    - images/Dogoszhi/
    - images/Flagstaff/
    - images/Tusayan/
    - images/Kayenta/
  uses-material-design: true
  fonts: 
    - family: Uber
      fonts:
        - asset: fonts/UberMoveBold.otf
          weight: 700
        - asset: fonts/UberMoveMedium.otf
          weight: 500