name: craft
description: Ceramic Sherd Classifier.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_cropper: ^5.0.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/
  uses-material-design: true
  fonts: 
    - family: Uber
      fonts:
        - asset: fonts/UberMoveBold.otf
          weight: 700
        - asset: fonts/UberMoveMedium.otf
          weight: 500